#ifndef XR1CONTROLLERPM_GLOBAL_H
#define XR1CONTROLLERPM_GLOBAL_H


#if defined(XR1CONTROLLERPM_LIBRARY)
#  define XR1CONTROLLERPMSHARED_EXPORT
#else
#  define XR1CONTROLLERPMSHARED_EXPORT
#endif

#endif // XR1CONTROLLERPM_GLOBAL_H
